accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),

    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

articles/models.py
from django.db import models
from accounts.models import User
from django.conf import settings
from django.contrib.auth import get_user_model

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    
    # 유저모델을 참조하는 방법
    # 1. 직접참조 (권장하지 않음)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)

    # 2. setting의 변수 활용
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # 3. get_user_model
    # user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        # fields = '__all__'
        fields = ('username',)


class CustomAuthenticationForm(AuthenticationForm):
    pass

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta():
        model = Article
        # fields = '__all__'
        # fields = ('title', 'contents',)
        exclude = ('user', )


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        # fields = '__all__'
        fields = ('content', )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .models import User
# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')

    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }

    return render(request, 'signup.html', context)


def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            # http://127.0.0.1:8000/accounts/login/
            # http://127.0.0.1:8000/accounts/login/?next=/articles/1/
            next_url = request.GET.get('next')
            # next 인자에 url이 없을 때 => None or 'articles:index'
            # next 인자에 url이 있을 때 => '/articles/1/' or 'articles:index'
            return redirect(next_url or 'articles:index')
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }

    return render(request, 'login.html', context)


def logout(request):
    auth_logout(request)

    return redirect('accounts:login')


def profile(request, username):

    user_profile = User.objects.get(username=username)

    context = {
        'user_profile': user_profile, 
    }

    return render(request, 'profile.html', context)

articles/views.py
from django.shortcuts import render, redirect
from .forms import ArticleForm, CommentForm
from .models import Article, Comment
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }

    return render(request, 'index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()

            return redirect('articles:index')
    else:
        form = ArticleForm()

    context = {
        'form': form,
    }

    return render(request, 'form.html', context)


@login_required
def detail(request, id):
    article = Article.objects.get(id=id)
    form = CommentForm()

    context = {
        'article': article,
        'form': form,
    }

    return render(request, 'detail.html', context)


def delete(request, id):
    article = Article.objects.get(id=id)
    if request.user == article.user:
        article.delete()

    return redirect('articles:index')


def update(request, id):
    article = Article.objects.get(id=id)

    if request.user != article.user:
        return redirect('articles:index')

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', id=id)
    else:
        form = ArticleForm(instance=article) 

    context = {
        'form': form,
    }

    return render(request, 'form.html', context)


def comment_create(request, article_id):
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)

        # 객체를 저장하는 경우
        # comment.user = request.user
        # article = Article.objects.get(id=article_id)
        # comment.article = article

        #id값만 저장하는 경우
        comment.user_id = request.user.id
        comment.article_id = article_id 

        comment.save()

        return redirect('articles:detail', id=article_id)


@login_required
def comment_delete(request, article_id, comment_id):

    comment = Comment.objects.get(id=comment_id)
    if request.user == comment.user:
        comment.delete()

    return redirect('articles:detail', id=article_id)

accounts/templates/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary">
    </form>

{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{user_profile}}</h1>

    <h1>작성한 게시물</h1>
    {% for article in user_profile.article_set.all %}
        <p>{{article.title}}</p>
    {% endfor %}

    <h1>작성한 댓글</h1>
    {% for comment in user_profile.comment_set.all %}
        <p>{{comment.article_id}} : {{comment.content}}</p>
    {% endfor %}


    {% for article in user_profile.article_set.all %}
        <h2>{{article.title}}</h2>
        {% for comment in article.comment_set.all %}
            <p>{{comment.content}}</p>
        {% endfor %}
    {% endfor %}

{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary">
    </form>
{% endblock %}

articles/templates/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <div class="card">
        <div class="card-header">
            <a href="{% url 'accounts:profile' username=article.user.username %}">{{article.user}}</a>
        </div>
        <div class="card-body">
            <h5 class="card-title">{{article.title}}</h5>
            <p class="card-text">{{article.content}}</p>
        </div>
        {% if user == article.user %}
        <div class="card-footer">
            <form class="d-inline" action="{% url 'articles:delete' id=article.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="delete" class="btn btn-danger">
            </form>
            <form class="d-inline" action="{% url 'articles:update' id=article.id %}">
                <input type="submit" value="update" class="btn btn-warning">
            </form>
        </div>
        {% endif %}
    </div>
    <hr>

    <form action="{% url 'articles:comment_create' article_id=article.id %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary">
    </form>

    <hr>

    {% for comment in article.comment_set.all %}
        <div class="alert alert-light">
            {{comment.user}} - {{comment.content}}

            {% if user == comment.user %}
            <form class="d-inline" action="{% url 'articles:comment_delete' article_id=article.id comment_id=comment.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="delete" class="btn btn-danger btn-sm">
            </form>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form%}
        <input type="submit" class="btn btn-primary">
    </form>
{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    {% for article in articles %}
        <div class="card my-3">
            <div class="card-header">
                <a class="text-decoration-none" href="{% url 'accounts:profile' username=article.user.username%}">{{article.user}}</a>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{article.title}}</h5>
                {% if user.is_authenticated %}
                    <a href="{% url 'articles:detail' id=article.id%}" class="btn btn-primary">detail</a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'articles:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-link disabled">{{user}}</a>
                    <a class="nav-link" href="{% url 'articles:create' %}">create</a>
                    <a class="nav-link" href="{% url 'accounts:logout' %}">logout</a>
                {% else %}
                    <a class="nav-link" href="{% url 'accounts:signup' %}">signup</a>
                    <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
                {% endif %}
            </div>
          </div>
        </div>
    </nav>

    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>